// Nexus-Match: Real-Time Matchmaking & Session Engine
// Protocol Buffers v3 definition for all three core services.
//
// Services:
//   1. PlayerGatewayService  — Bi-directional stream for heartbeat & queue status broadcast
//   2. MatchmakerService     — Internal queue management (exposed for admin/debug)
//   3. SessionTrackerService — Unary endpoint for submitting final match results

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.1
// source: nexus.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerGatewayService_EnterMatchmaking_FullMethodName = "/nexus.PlayerGatewayService/EnterMatchmaking"
)

// PlayerGatewayServiceClient is the client API for PlayerGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlayerGatewayService is the single entry point for every game client.
// The bi-directional stream keeps the connection alive, broadcasts queue
// status, and delivers the final match assignment.
type PlayerGatewayServiceClient interface {
	// EnterMatchmaking opens a persistent bi-di stream.
	// Client sends JoinQueue → Heartbeats; Server pushes status updates.
	EnterMatchmaking(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayRequest, GatewayResponse], error)
}

type playerGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerGatewayServiceClient(cc grpc.ClientConnInterface) PlayerGatewayServiceClient {
	return &playerGatewayServiceClient{cc}
}

func (c *playerGatewayServiceClient) EnterMatchmaking(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GatewayRequest, GatewayResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerGatewayService_ServiceDesc.Streams[0], PlayerGatewayService_EnterMatchmaking_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GatewayRequest, GatewayResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerGatewayService_EnterMatchmakingClient = grpc.BidiStreamingClient[GatewayRequest, GatewayResponse]

// PlayerGatewayServiceServer is the server API for PlayerGatewayService service.
// All implementations must embed UnimplementedPlayerGatewayServiceServer
// for forward compatibility.
//
// PlayerGatewayService is the single entry point for every game client.
// The bi-directional stream keeps the connection alive, broadcasts queue
// status, and delivers the final match assignment.
type PlayerGatewayServiceServer interface {
	// EnterMatchmaking opens a persistent bi-di stream.
	// Client sends JoinQueue → Heartbeats; Server pushes status updates.
	EnterMatchmaking(grpc.BidiStreamingServer[GatewayRequest, GatewayResponse]) error
	mustEmbedUnimplementedPlayerGatewayServiceServer()
}

// UnimplementedPlayerGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerGatewayServiceServer struct{}

func (UnimplementedPlayerGatewayServiceServer) EnterMatchmaking(grpc.BidiStreamingServer[GatewayRequest, GatewayResponse]) error {
	return status.Error(codes.Unimplemented, "method EnterMatchmaking not implemented")
}
func (UnimplementedPlayerGatewayServiceServer) mustEmbedUnimplementedPlayerGatewayServiceServer() {}
func (UnimplementedPlayerGatewayServiceServer) testEmbeddedByValue()                              {}

// UnsafePlayerGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerGatewayServiceServer will
// result in compilation errors.
type UnsafePlayerGatewayServiceServer interface {
	mustEmbedUnimplementedPlayerGatewayServiceServer()
}

func RegisterPlayerGatewayServiceServer(s grpc.ServiceRegistrar, srv PlayerGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerGatewayService_ServiceDesc, srv)
}

func _PlayerGatewayService_EnterMatchmaking_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerGatewayServiceServer).EnterMatchmaking(&grpc.GenericServerStream[GatewayRequest, GatewayResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerGatewayService_EnterMatchmakingServer = grpc.BidiStreamingServer[GatewayRequest, GatewayResponse]

// PlayerGatewayService_ServiceDesc is the grpc.ServiceDesc for PlayerGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.PlayerGatewayService",
	HandlerType: (*PlayerGatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EnterMatchmaking",
			Handler:       _PlayerGatewayService_EnterMatchmaking_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nexus.proto",
}

const (
	MatchmakerService_GetQueueStats_FullMethodName = "/nexus.MatchmakerService/GetQueueStats"
	MatchmakerService_ForceMatch_FullMethodName    = "/nexus.MatchmakerService/ForceMatch"
)

// MatchmakerServiceClient is the client API for MatchmakerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchmakerService exposes observability + admin controls.
// In production this would sit behind an internal-only listener.
type MatchmakerServiceClient interface {
	GetQueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error)
	ForceMatch(ctx context.Context, in *ForceMatchRequest, opts ...grpc.CallOption) (*ForceMatchResponse, error)
}

type matchmakerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakerServiceClient(cc grpc.ClientConnInterface) MatchmakerServiceClient {
	return &matchmakerServiceClient{cc}
}

func (c *matchmakerServiceClient) GetQueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStatsResponse)
	err := c.cc.Invoke(ctx, MatchmakerService_GetQueueStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakerServiceClient) ForceMatch(ctx context.Context, in *ForceMatchRequest, opts ...grpc.CallOption) (*ForceMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceMatchResponse)
	err := c.cc.Invoke(ctx, MatchmakerService_ForceMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchmakerServiceServer is the server API for MatchmakerService service.
// All implementations must embed UnimplementedMatchmakerServiceServer
// for forward compatibility.
//
// MatchmakerService exposes observability + admin controls.
// In production this would sit behind an internal-only listener.
type MatchmakerServiceServer interface {
	GetQueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error)
	ForceMatch(context.Context, *ForceMatchRequest) (*ForceMatchResponse, error)
	mustEmbedUnimplementedMatchmakerServiceServer()
}

// UnimplementedMatchmakerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakerServiceServer struct{}

func (UnimplementedMatchmakerServiceServer) GetQueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueueStats not implemented")
}
func (UnimplementedMatchmakerServiceServer) ForceMatch(context.Context, *ForceMatchRequest) (*ForceMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceMatch not implemented")
}
func (UnimplementedMatchmakerServiceServer) mustEmbedUnimplementedMatchmakerServiceServer() {}
func (UnimplementedMatchmakerServiceServer) testEmbeddedByValue()                           {}

// UnsafeMatchmakerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakerServiceServer will
// result in compilation errors.
type UnsafeMatchmakerServiceServer interface {
	mustEmbedUnimplementedMatchmakerServiceServer()
}

func RegisterMatchmakerServiceServer(s grpc.ServiceRegistrar, srv MatchmakerServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchmakerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchmakerService_ServiceDesc, srv)
}

func _MatchmakerService_GetQueueStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakerServiceServer).GetQueueStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakerService_GetQueueStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakerServiceServer).GetQueueStats(ctx, req.(*QueueStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakerService_ForceMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakerServiceServer).ForceMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakerService_ForceMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakerServiceServer).ForceMatch(ctx, req.(*ForceMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchmakerService_ServiceDesc is the grpc.ServiceDesc for MatchmakerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.MatchmakerService",
	HandlerType: (*MatchmakerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQueueStats",
			Handler:    _MatchmakerService_GetQueueStats_Handler,
		},
		{
			MethodName: "ForceMatch",
			Handler:    _MatchmakerService_ForceMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}

const (
	SessionTrackerService_SubmitResult_FullMethodName = "/nexus.SessionTrackerService/SubmitResult"
	SessionTrackerService_GetSession_FullMethodName   = "/nexus.SessionTrackerService/GetSession"
)

// SessionTrackerServiceClient is the client API for SessionTrackerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionTrackerService records match outcomes via Unary RPCs.
type SessionTrackerServiceClient interface {
	SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionSummary, error)
}

type sessionTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionTrackerServiceClient(cc grpc.ClientConnInterface) SessionTrackerServiceClient {
	return &sessionTrackerServiceClient{cc}
}

func (c *sessionTrackerServiceClient) SubmitResult(ctx context.Context, in *SubmitResultRequest, opts ...grpc.CallOption) (*SubmitResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResultResponse)
	err := c.cc.Invoke(ctx, SessionTrackerService_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionTrackerServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionSummary)
	err := c.cc.Invoke(ctx, SessionTrackerService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionTrackerServiceServer is the server API for SessionTrackerService service.
// All implementations must embed UnimplementedSessionTrackerServiceServer
// for forward compatibility.
//
// SessionTrackerService records match outcomes via Unary RPCs.
type SessionTrackerServiceServer interface {
	SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionSummary, error)
	mustEmbedUnimplementedSessionTrackerServiceServer()
}

// UnimplementedSessionTrackerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionTrackerServiceServer struct{}

func (UnimplementedSessionTrackerServiceServer) SubmitResult(context.Context, *SubmitResultRequest) (*SubmitResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedSessionTrackerServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSessionTrackerServiceServer) mustEmbedUnimplementedSessionTrackerServiceServer() {}
func (UnimplementedSessionTrackerServiceServer) testEmbeddedByValue()                               {}

// UnsafeSessionTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionTrackerServiceServer will
// result in compilation errors.
type UnsafeSessionTrackerServiceServer interface {
	mustEmbedUnimplementedSessionTrackerServiceServer()
}

func RegisterSessionTrackerServiceServer(s grpc.ServiceRegistrar, srv SessionTrackerServiceServer) {
	// If the following call panics, it indicates UnimplementedSessionTrackerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionTrackerService_ServiceDesc, srv)
}

func _SessionTrackerService_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionTrackerServiceServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionTrackerService_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionTrackerServiceServer).SubmitResult(ctx, req.(*SubmitResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionTrackerService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionTrackerServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionTrackerService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionTrackerServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionTrackerService_ServiceDesc is the grpc.ServiceDesc for SessionTrackerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.SessionTrackerService",
	HandlerType: (*SessionTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResult",
			Handler:    _SessionTrackerService_SubmitResult_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SessionTrackerService_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}
