// Nexus-Match: Real-Time Matchmaking & Session Engine
// Protocol Buffers v3 definition for all three core services.
//
// Services:
//   1. PlayerGatewayService  — Bi-directional stream for heartbeat & queue status broadcast
//   2. MatchmakerService     — Internal queue management (exposed for admin/debug)
//   3. SessionTrackerService — Unary endpoint for submitting final match results

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: nexus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueStatus represents every discrete state a player can occupy
// from the moment they join the queue until the match concludes.
type QueueStatus int32

const (
	QueueStatus_QUEUE_STATUS_UNSPECIFIED QueueStatus = 0
	QueueStatus_QUEUE_STATUS_WAITING     QueueStatus = 1 // Player is in the pool, waiting for opponents
	QueueStatus_QUEUE_STATUS_MATCHED     QueueStatus = 2 // A match has been found, session is being created
	QueueStatus_QUEUE_STATUS_IN_GAME     QueueStatus = 3 // Players are inside an active session
	QueueStatus_QUEUE_STATUS_COMPLETED   QueueStatus = 4 // The session has ended normally
	QueueStatus_QUEUE_STATUS_CANCELLED   QueueStatus = 5 // Player or server cancelled the search
	QueueStatus_QUEUE_STATUS_ERROR       QueueStatus = 6 // An unrecoverable error occurred
)

// Enum value maps for QueueStatus.
var (
	QueueStatus_name = map[int32]string{
		0: "QUEUE_STATUS_UNSPECIFIED",
		1: "QUEUE_STATUS_WAITING",
		2: "QUEUE_STATUS_MATCHED",
		3: "QUEUE_STATUS_IN_GAME",
		4: "QUEUE_STATUS_COMPLETED",
		5: "QUEUE_STATUS_CANCELLED",
		6: "QUEUE_STATUS_ERROR",
	}
	QueueStatus_value = map[string]int32{
		"QUEUE_STATUS_UNSPECIFIED": 0,
		"QUEUE_STATUS_WAITING":     1,
		"QUEUE_STATUS_MATCHED":     2,
		"QUEUE_STATUS_IN_GAME":     3,
		"QUEUE_STATUS_COMPLETED":   4,
		"QUEUE_STATUS_CANCELLED":   5,
		"QUEUE_STATUS_ERROR":       6,
	}
)

func (x QueueStatus) Enum() *QueueStatus {
	p := new(QueueStatus)
	*p = x
	return p
}

func (x QueueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[0].Descriptor()
}

func (QueueStatus) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[0]
}

func (x QueueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueStatus.Descriptor instead.
func (QueueStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

// MatchResult enumerates the possible outcomes for a player in a finished session.
type MatchResult int32

const (
	MatchResult_MATCH_RESULT_UNSPECIFIED MatchResult = 0
	MatchResult_MATCH_RESULT_WIN         MatchResult = 1
	MatchResult_MATCH_RESULT_LOSS        MatchResult = 2
	MatchResult_MATCH_RESULT_DRAW        MatchResult = 3
)

// Enum value maps for MatchResult.
var (
	MatchResult_name = map[int32]string{
		0: "MATCH_RESULT_UNSPECIFIED",
		1: "MATCH_RESULT_WIN",
		2: "MATCH_RESULT_LOSS",
		3: "MATCH_RESULT_DRAW",
	}
	MatchResult_value = map[string]int32{
		"MATCH_RESULT_UNSPECIFIED": 0,
		"MATCH_RESULT_WIN":         1,
		"MATCH_RESULT_LOSS":        2,
		"MATCH_RESULT_DRAW":        3,
	}
)

func (x MatchResult) Enum() *MatchResult {
	p := new(MatchResult)
	*p = x
	return p
}

func (x MatchResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchResult) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[1].Descriptor()
}

func (MatchResult) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[1]
}

func (x MatchResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchResult.Descriptor instead.
func (MatchResult) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

// PlayerInfo carries the immutable identity + mutable rating of a player.
// MMR (Match-Making Rating) is an int32 to avoid floating-point comparison
// overhead and keep allocations tight.
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`          // UUID v4, assigned client-side
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // Human-readable tag
	Mmr           int32                  `protobuf:"varint,3,opt,name=mmr,proto3" json:"mmr,omitempty"`                                   // Matchmaking rating, range [0, 10000]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PlayerInfo) GetMmr() int32 {
	if x != nil {
		return x.Mmr
	}
	return 0
}

// GatewayRequest is the client→server half of the bi-directional stream.
// The first message MUST carry join_queue; subsequent messages are heartbeats
// or explicit cancellations.
type GatewayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*GatewayRequest_JoinQueue
	//	*GatewayRequest_Heartbeat
	//	*GatewayRequest_CancelQueue
	Action        isGatewayRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRequest) Reset() {
	*x = GatewayRequest{}
	mi := &file_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRequest) ProtoMessage() {}

func (x *GatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRequest.ProtoReflect.Descriptor instead.
func (*GatewayRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayRequest) GetAction() isGatewayRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *GatewayRequest) GetJoinQueue() *JoinQueueAction {
	if x != nil {
		if x, ok := x.Action.(*GatewayRequest_JoinQueue); ok {
			return x.JoinQueue
		}
	}
	return nil
}

func (x *GatewayRequest) GetHeartbeat() *HeartbeatAction {
	if x != nil {
		if x, ok := x.Action.(*GatewayRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *GatewayRequest) GetCancelQueue() *CancelQueueAction {
	if x != nil {
		if x, ok := x.Action.(*GatewayRequest_CancelQueue); ok {
			return x.CancelQueue
		}
	}
	return nil
}

type isGatewayRequest_Action interface {
	isGatewayRequest_Action()
}

type GatewayRequest_JoinQueue struct {
	JoinQueue *JoinQueueAction `protobuf:"bytes,1,opt,name=join_queue,json=joinQueue,proto3,oneof"` // Initial: enqueue the player
}

type GatewayRequest_Heartbeat struct {
	Heartbeat *HeartbeatAction `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // Periodic keep-alive
}

type GatewayRequest_CancelQueue struct {
	CancelQueue *CancelQueueAction `protobuf:"bytes,3,opt,name=cancel_queue,json=cancelQueue,proto3,oneof"` // Player wants out
}

func (*GatewayRequest_JoinQueue) isGatewayRequest_Action() {}

func (*GatewayRequest_Heartbeat) isGatewayRequest_Action() {}

func (*GatewayRequest_CancelQueue) isGatewayRequest_Action() {}

type JoinQueueAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueAction) Reset() {
	*x = JoinQueueAction{}
	mi := &file_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueAction) ProtoMessage() {}

func (x *JoinQueueAction) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueAction.ProtoReflect.Descriptor instead.
func (*JoinQueueAction) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *JoinQueueAction) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type HeartbeatAction struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestampMs int64                  `protobuf:"varint,1,opt,name=client_timestamp_ms,json=clientTimestampMs,proto3" json:"client_timestamp_ms,omitempty"` // Unix millis, lets server measure drift
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatAction) Reset() {
	*x = HeartbeatAction{}
	mi := &file_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAction) ProtoMessage() {}

func (x *HeartbeatAction) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAction.ProtoReflect.Descriptor instead.
func (*HeartbeatAction) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatAction) GetClientTimestampMs() int64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

type CancelQueueAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueueAction) Reset() {
	*x = CancelQueueAction{}
	mi := &file_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueueAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueueAction) ProtoMessage() {}

func (x *CancelQueueAction) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueueAction.ProtoReflect.Descriptor instead.
func (*CancelQueueAction) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *CancelQueueAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CancelQueueAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GatewayResponse is the server→client half. The server pushes status
// updates and, ultimately, the match assignment.
type GatewayResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            QueueStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=nexus.QueueStatus" json:"status,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                   // Human-readable context
	QueuePosition     int32                  `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"` // Approximate position (0 = unknown)
	ServerTimestampMs int64                  `protobuf:"varint,4,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`
	Match             *MatchAssignment       `protobuf:"bytes,5,opt,name=match,proto3" json:"match,omitempty"` // Non-nil only when status == MATCHED
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayResponse) GetStatus() QueueStatus {
	if x != nil {
		return x.Status
	}
	return QueueStatus_QUEUE_STATUS_UNSPECIFIED
}

func (x *GatewayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GatewayResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *GatewayResponse) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *GatewayResponse) GetMatch() *MatchAssignment {
	if x != nil {
		return x.Match
	}
	return nil
}

// MatchAssignment contains everything a client needs to transition into a game.
type MatchAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`          // Globally unique session identifier
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`          // All player IDs in this match
	CreatedAtMs   int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"` // Session creation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchAssignment) Reset() {
	*x = MatchAssignment{}
	mi := &file_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchAssignment) ProtoMessage() {}

func (x *MatchAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchAssignment.ProtoReflect.Descriptor instead.
func (*MatchAssignment) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *MatchAssignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchAssignment) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchAssignment) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// QueueStatsRequest is intentionally empty; stats are global.
type QueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsRequest) Reset() {
	*x = QueueStatsRequest{}
	mi := &file_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsRequest) ProtoMessage() {}

func (x *QueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsRequest.ProtoReflect.Descriptor instead.
func (*QueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{7}
}

type QueueStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalWaiting   int32                  `protobuf:"varint,1,opt,name=total_waiting,json=totalWaiting,proto3" json:"total_waiting,omitempty"`
	TotalMatched   int32                  `protobuf:"varint,2,opt,name=total_matched,json=totalMatched,proto3" json:"total_matched,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	mi := &file_nexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsResponse.ProtoReflect.Descriptor instead.
func (*QueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{8}
}

func (x *QueueStatsResponse) GetTotalWaiting() int32 {
	if x != nil {
		return x.TotalWaiting
	}
	return 0
}

func (x *QueueStatsResponse) GetTotalMatched() int32 {
	if x != nil {
		return x.TotalMatched
	}
	return 0
}

func (x *QueueStatsResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

// ForceMatchRequest lets an admin/test harness trigger an immediate match cycle.
type ForceMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceMatchRequest) Reset() {
	*x = ForceMatchRequest{}
	mi := &file_nexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceMatchRequest) ProtoMessage() {}

func (x *ForceMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceMatchRequest.ProtoReflect.Descriptor instead.
func (*ForceMatchRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{9}
}

type ForceMatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MatchesCreated int32                  `protobuf:"varint,1,opt,name=matches_created,json=matchesCreated,proto3" json:"matches_created,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForceMatchResponse) Reset() {
	*x = ForceMatchResponse{}
	mi := &file_nexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceMatchResponse) ProtoMessage() {}

func (x *ForceMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceMatchResponse.ProtoReflect.Descriptor instead.
func (*ForceMatchResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{10}
}

func (x *ForceMatchResponse) GetMatchesCreated() int32 {
	if x != nil {
		return x.MatchesCreated
	}
	return 0
}

// SubmitResultRequest is sent by a client (or game server) once the match ends.
type SubmitResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Result        MatchResult            `protobuf:"varint,3,opt,name=result,proto3,enum=nexus.MatchResult" json:"result,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                          // In-game score (arbitrary units)
	DurationS     int32                  `protobuf:"varint,5,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"` // Match duration in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultRequest) Reset() {
	*x = SubmitResultRequest{}
	mi := &file_nexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultRequest) ProtoMessage() {}

func (x *SubmitResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitResultRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitResultRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SubmitResultRequest) GetResult() MatchResult {
	if x != nil {
		return x.Result
	}
	return MatchResult_MATCH_RESULT_UNSPECIFIED
}

func (x *SubmitResultRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitResultRequest) GetDurationS() int32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

type SubmitResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewMmr        int32                  `protobuf:"varint,3,opt,name=new_mmr,json=newMmr,proto3" json:"new_mmr,omitempty"` // Updated MMR after the result is applied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResultResponse) Reset() {
	*x = SubmitResultResponse{}
	mi := &file_nexus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResultResponse) ProtoMessage() {}

func (x *SubmitResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitResultResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitResultResponse) GetNewMmr() int32 {
	if x != nil {
		return x.NewMmr
	}
	return 0
}

// GetSessionRequest retrieves summary data for a completed session.
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_nexus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Results       []*PlayerResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,3,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	EndedAtMs     int64                  `protobuf:"varint,4,opt,name=ended_at_ms,json=endedAtMs,proto3" json:"ended_at_ms,omitempty"`
	Finalized     bool                   `protobuf:"varint,5,opt,name=finalized,proto3" json:"finalized,omitempty"` // true once all players submitted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_nexus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{14}
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetResults() []*PlayerResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SessionSummary) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *SessionSummary) GetEndedAtMs() int64 {
	if x != nil {
		return x.EndedAtMs
	}
	return 0
}

func (x *SessionSummary) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

type PlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Result        MatchResult            `protobuf:"varint,2,opt,name=result,proto3,enum=nexus.MatchResult" json:"result,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	MmrDelta      int32                  `protobuf:"varint,4,opt,name=mmr_delta,json=mmrDelta,proto3" json:"mmr_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_nexus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerResult) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerResult) GetResult() MatchResult {
	if x != nil {
		return x.Result
	}
	return MatchResult_MATCH_RESULT_UNSPECIFIED
}

func (x *PlayerResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerResult) GetMmrDelta() int32 {
	if x != nil {
		return x.MmrDelta
	}
	return 0
}

var File_nexus_proto protoreflect.FileDescriptor

const file_nexus_proto_rawDesc = "" +
	"\n" +
	"\vnexus.proto\x12\x05nexus\"^\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03mmr\x18\x03 \x01(\x05R\x03mmr\"\xca\x01\n" +
	"\x0eGatewayRequest\x127\n" +
	"\n" +
	"join_queue\x18\x01 \x01(\v2\x16.nexus.JoinQueueActionH\x00R\tjoinQueue\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.nexus.HeartbeatActionH\x00R\theartbeat\x12=\n" +
	"\fcancel_queue\x18\x03 \x01(\v2\x18.nexus.CancelQueueActionH\x00R\vcancelQueueB\b\n" +
	"\x06action\"<\n" +
	"\x0fJoinQueueAction\x12)\n" +
	"\x06player\x18\x01 \x01(\v2\x11.nexus.PlayerInfoR\x06player\"A\n" +
	"\x0fHeartbeatAction\x12.\n" +
	"\x13client_timestamp_ms\x18\x01 \x01(\x03R\x11clientTimestampMs\"H\n" +
	"\x11CancelQueueAction\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xdc\x01\n" +
	"\x0fGatewayResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.nexus.QueueStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x05R\rqueuePosition\x12.\n" +
	"\x13server_timestamp_ms\x18\x04 \x01(\x03R\x11serverTimestampMs\x12,\n" +
	"\x05match\x18\x05 \x01(\v2\x16.nexus.MatchAssignmentR\x05match\"s\n" +
	"\x0fMatchAssignment\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\"\x13\n" +
	"\x11QueueStatsRequest\"\x87\x01\n" +
	"\x12QueueStatsResponse\x12#\n" +
	"\rtotal_waiting\x18\x01 \x01(\x05R\ftotalWaiting\x12#\n" +
	"\rtotal_matched\x18\x02 \x01(\x05R\ftotalMatched\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\"\x13\n" +
	"\x11ForceMatchRequest\"=\n" +
	"\x12ForceMatchResponse\x12'\n" +
	"\x0fmatches_created\x18\x01 \x01(\x05R\x0ematchesCreated\"\xb2\x01\n" +
	"\x13SubmitResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12*\n" +
	"\x06result\x18\x03 \x01(\x0e2\x12.nexus.MatchResultR\x06result\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x05 \x01(\x05R\tdurationS\"e\n" +
	"\x14SubmitResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anew_mmr\x18\x03 \x01(\x05R\x06newMmr\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc0\x01\n" +
	"\x0eSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\aresults\x18\x02 \x03(\v2\x13.nexus.PlayerResultR\aresults\x12\"\n" +
	"\rstarted_at_ms\x18\x03 \x01(\x03R\vstartedAtMs\x12\x1e\n" +
	"\vended_at_ms\x18\x04 \x01(\x03R\tendedAtMs\x12\x1c\n" +
	"\tfinalized\x18\x05 \x01(\bR\tfinalized\"\x8a\x01\n" +
	"\fPlayerResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12*\n" +
	"\x06result\x18\x02 \x01(\x0e2\x12.nexus.MatchResultR\x06result\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1b\n" +
	"\tmmr_delta\x18\x04 \x01(\x05R\bmmrDelta*\xc9\x01\n" +
	"\vQueueStatus\x12\x1c\n" +
	"\x18QUEUE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUEUE_STATUS_WAITING\x10\x01\x12\x18\n" +
	"\x14QUEUE_STATUS_MATCHED\x10\x02\x12\x18\n" +
	"\x14QUEUE_STATUS_IN_GAME\x10\x03\x12\x1a\n" +
	"\x16QUEUE_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16QUEUE_STATUS_CANCELLED\x10\x05\x12\x16\n" +
	"\x12QUEUE_STATUS_ERROR\x10\x06*o\n" +
	"\vMatchResult\x12\x1c\n" +
	"\x18MATCH_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MATCH_RESULT_WIN\x10\x01\x12\x15\n" +
	"\x11MATCH_RESULT_LOSS\x10\x02\x12\x15\n" +
	"\x11MATCH_RESULT_DRAW\x10\x032]\n" +
	"\x14PlayerGatewayService\x12E\n" +
	"\x10EnterMatchmaking\x12\x15.nexus.GatewayRequest\x1a\x16.nexus.GatewayResponse(\x010\x012\x9c\x01\n" +
	"\x11MatchmakerService\x12D\n" +
	"\rGetQueueStats\x12\x18.nexus.QueueStatsRequest\x1a\x19.nexus.QueueStatsResponse\x12A\n" +
	"\n" +
	"ForceMatch\x12\x18.nexus.ForceMatchRequest\x1a\x19.nexus.ForceMatchResponse2\x9f\x01\n" +
	"\x15SessionTrackerService\x12G\n" +
	"\fSubmitResult\x12\x1a.nexus.SubmitResultRequest\x1a\x1b.nexus.SubmitResultResponse\x12=\n" +
	"\n" +
	"GetSession\x12\x18.nexus.GetSessionRequest\x1a\x15.nexus.SessionSummaryB\x14Z\x12nexus-match/pkg/pbb\x06proto3"

var (
	file_nexus_proto_rawDescOnce sync.Once
	file_nexus_proto_rawDescData []byte
)

func file_nexus_proto_rawDescGZIP() []byte {
	file_nexus_proto_rawDescOnce.Do(func() {
		file_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)))
	})
	return file_nexus_proto_rawDescData
}

var file_nexus_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_nexus_proto_goTypes = []any{
	(QueueStatus)(0),             // 0: nexus.QueueStatus
	(MatchResult)(0),             // 1: nexus.MatchResult
	(*PlayerInfo)(nil),           // 2: nexus.PlayerInfo
	(*GatewayRequest)(nil),       // 3: nexus.GatewayRequest
	(*JoinQueueAction)(nil),      // 4: nexus.JoinQueueAction
	(*HeartbeatAction)(nil),      // 5: nexus.HeartbeatAction
	(*CancelQueueAction)(nil),    // 6: nexus.CancelQueueAction
	(*GatewayResponse)(nil),      // 7: nexus.GatewayResponse
	(*MatchAssignment)(nil),      // 8: nexus.MatchAssignment
	(*QueueStatsRequest)(nil),    // 9: nexus.QueueStatsRequest
	(*QueueStatsResponse)(nil),   // 10: nexus.QueueStatsResponse
	(*ForceMatchRequest)(nil),    // 11: nexus.ForceMatchRequest
	(*ForceMatchResponse)(nil),   // 12: nexus.ForceMatchResponse
	(*SubmitResultRequest)(nil),  // 13: nexus.SubmitResultRequest
	(*SubmitResultResponse)(nil), // 14: nexus.SubmitResultResponse
	(*GetSessionRequest)(nil),    // 15: nexus.GetSessionRequest
	(*SessionSummary)(nil),       // 16: nexus.SessionSummary
	(*PlayerResult)(nil),         // 17: nexus.PlayerResult
}
var file_nexus_proto_depIdxs = []int32{
	4,  // 0: nexus.GatewayRequest.join_queue:type_name -> nexus.JoinQueueAction
	5,  // 1: nexus.GatewayRequest.heartbeat:type_name -> nexus.HeartbeatAction
	6,  // 2: nexus.GatewayRequest.cancel_queue:type_name -> nexus.CancelQueueAction
	2,  // 3: nexus.JoinQueueAction.player:type_name -> nexus.PlayerInfo
	0,  // 4: nexus.GatewayResponse.status:type_name -> nexus.QueueStatus
	8,  // 5: nexus.GatewayResponse.match:type_name -> nexus.MatchAssignment
	1,  // 6: nexus.SubmitResultRequest.result:type_name -> nexus.MatchResult
	17, // 7: nexus.SessionSummary.results:type_name -> nexus.PlayerResult
	1,  // 8: nexus.PlayerResult.result:type_name -> nexus.MatchResult
	3,  // 9: nexus.PlayerGatewayService.EnterMatchmaking:input_type -> nexus.GatewayRequest
	9,  // 10: nexus.MatchmakerService.GetQueueStats:input_type -> nexus.QueueStatsRequest
	11, // 11: nexus.MatchmakerService.ForceMatch:input_type -> nexus.ForceMatchRequest
	13, // 12: nexus.SessionTrackerService.SubmitResult:input_type -> nexus.SubmitResultRequest
	15, // 13: nexus.SessionTrackerService.GetSession:input_type -> nexus.GetSessionRequest
	7,  // 14: nexus.PlayerGatewayService.EnterMatchmaking:output_type -> nexus.GatewayResponse
	10, // 15: nexus.MatchmakerService.GetQueueStats:output_type -> nexus.QueueStatsResponse
	12, // 16: nexus.MatchmakerService.ForceMatch:output_type -> nexus.ForceMatchResponse
	14, // 17: nexus.SessionTrackerService.SubmitResult:output_type -> nexus.SubmitResultResponse
	16, // 18: nexus.SessionTrackerService.GetSession:output_type -> nexus.SessionSummary
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nexus_proto_init() }
func file_nexus_proto_init() {
	if File_nexus_proto != nil {
		return
	}
	file_nexus_proto_msgTypes[1].OneofWrappers = []any{
		(*GatewayRequest_JoinQueue)(nil),
		(*GatewayRequest_Heartbeat)(nil),
		(*GatewayRequest_CancelQueue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_nexus_proto_goTypes,
		DependencyIndexes: file_nexus_proto_depIdxs,
		EnumInfos:         file_nexus_proto_enumTypes,
		MessageInfos:      file_nexus_proto_msgTypes,
	}.Build()
	File_nexus_proto = out.File
	file_nexus_proto_goTypes = nil
	file_nexus_proto_depIdxs = nil
}
